### ISSUE TITLE
Spawn EACCESS error

### ISSUE THREAD

**Issue by infinite4evr** [scionoftech/webp-converter#28]
The latest commit breaks the package and It's not working fine 

```
Error: spawn /home/sticker_download_bot/node_modules/webp-converter/bin/libwebp_linux/bin/dwebp EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn /home/sticker_download_bot/node_modules/webp-converter/bin/libwebp_linux/bin/dwebp',
  path: '/home/sticker_download_bot/node_modules/webp-converter/bin/libwebp_linux/bin/dwebp',
  spawnargs: [
    '/home/sticker_download_bot/temp/330959283/file_375.webp',
    '-o',
    '/home/sticker_download_bot/temp/330959283/octopusagad3.png'
  ],
  cmd: '/home/sticker_download_bot/node_modules/webp-converter/bin/libwebp_linux/bin/dwebp /home/sticker_download_bot/temp/330959283/file_375.webp -o /home/sticker_download_bot/temp/330959283/octopusagad3.png'                                                                                       
}
Error: spawn /home/sticker_download_bot/node_modules/webp-converter/bin/libwebp_linux/bin/dwebp EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn /home/sticker_download_bot/node_modules/webp-converter/bin/libwebp_linux/bin/dwebp',
  path: '/home/sticker_download_bot/node_modules/webp-converter/bin/libwebp_linux/bin/dwebp',
  spawnargs: [
    '/home/sticker_download_bot/temp/330959283/file_375.webp',
    '-o',
    '/home/sticker_download_bot/temp/330959283/octopusagad3.jpeg'
  ],
  cmd: '/home/sticker_download_bot/node_modules/webp-converter/bin/libwebp_linux/bin/dwebp /home/sticker_download_bot/temp/330959283/file_375.webp -o /home/sticker_download_bot/temp/330959283/octopusagad3.jpeg'
}
```

I have rolled back to version 2.2.3 for now.

**Comment by anthinkingcoder** [comment]
chmod +x /home/converterbot/node_modules/webp-converter/bin/libwebp_linux/bin/dwebp

**Comment by sbalko** [comment]
Can the binaries please be packaged with the right file permissions?

**Comment by scionoftech** [comment]
EACCES is the executable bit on the bundled binaries — call `webp.grant_permission()` once before converting (now documented in the README and usage guide). On Alpine, use a musl libwebp build via `setBinaryDir()`. Closing — please reopen if it persists after that. 🙏
