### ISSUE TITLE
spawn /webp-converter/bin/libwebp_linux/bin/cwebp EACCES 

### ISSUE THREAD

**Issue by Caesar73** [scionoftech/webp-converter#31]
-q 80 /tmp/pvSrBTKjwsl71LDvgcFlrIto.png -o /tmp/pvSrBTKjwsl71LDvgcFlrIto.png
Error: spawn /minio-server/node_modules/webp-converter/bin/libwebp_linux/bin/cwebp EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn /minio-server/node_modules/webp-converter/bin/libwebp_linux/bin/cwebp',
  path: '/minio-server/node_modules/webp-converter/bin/libwebp_linux/bin/cwebp',
  spawnargs: [
    '-q',
    '80',
    '/tmp/pvSrBTKjwsl71LDvgcFlrIto.png',
    '-o',
    '/tmp/pvSrBTKjwsl71LDvgcFlrIto.png'
  ],
  cmd: '/minio-server/node_modules/webp-converter/bin/libwebp_linux/bin/cwebp -q 80 /tmp/pvSrBTKjwsl71LDvgcFlrIto.png -o /tmp/pvSrBTKjwsl71LDvgcFlrIto.png'
}

**Comment by scionoftech** [comment]
EACCES → call `webp.grant_permission()` once before converting (documented now). On Alpine the bundled binaries are glibc, so use a musl build via `setBinaryDir()`. Closing — reopen if you still see it. 🙏
