### ISSUE TITLE
Multiple input files specified. Exiting due to command-line parsing error.

### ISSUE THREAD

**Issue by kaqiinono** [scionoftech/webp-converter#32]
```
 /Users/meinuo/project/vue/odyssey-server/node_modules/webp-converter/bin/libwebp_osx/bin/webpmux -frame /var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-360.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-15.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-30.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-45.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-60.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-75.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-90.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-105.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-120.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-135.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-150.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-165.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-180.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-195.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-210.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-225.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-240.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-255.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-270.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-285.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-300.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-315.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-330.webp +1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-345.webp +1000+0+0+0-b -loop 0 -bgcolor 255,255,255,255 -o /var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/zxcvcx.webp
ERROR at '+1000+0+0+0-b,/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-45.webp': Multiple input files specified.
Exiting due to command-line parsing error.
```
![image](https://user-images.githubusercontent.com/11257690/93190616-2825f800-f776-11ea-87e3-8ddb188c675c.png)

input array contains three pics it works well, but when more than three pics it went wrong.
please help

**Comment by kaqiinono** [comment]
after upgrade to 2.3.4 
new errors occur:

```
-frame /var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-360.webp +1000+0+0+0-b -frame "/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-15.webp +1000+0+0+0-b"
Error: Command failed: "/Users/meinuo/project/vue/odyssey-server/node_modules/webp-converter/bin/libwebp_osx/bin/webpmux" -frame /var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-360.webp +1000+0+0+0-b -frame "/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-15.webp +1000+0+0+0-b" -loop 0 -bgcolor 0,255,255,255 -o "/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/zxcvcx.webp"
cannot open input file '/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-15.webp +1000+0+0+0-b'

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '"/Users/meinuo/project/vue/odyssey-server/node_modules/webp-converter/bin/libwebp_osx/bin/webpmux" -frame /var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-360.webp +1000+0+0+0-b -frame "/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-15.webp +1000+0+0+0-b" -loop 0 -bgcolor 0,255,255,255 -o "/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/zxcvcx.webp"'
}
cannot open input file '/var/folders/cx/whqxnf0s22v8v5q9rx4npb0w0000gp/T/tmp-5889-STHAln2loxs1/cut-15.webp +1000+0+0+0-b'

```

but run cmd with one pic, it went well (pic does exist) it happens when input array contains more than one pics

**Comment by kaqiinono** [comment]
![image](https://user-images.githubusercontent.com/11257690/93195035-58bc6080-f77b-11ea-8e8c-2bf9eb894de6.png)


this line cause the problem, you should fixed it

**Comment by scionoftech** [comment]
The 'Multiple input files' error came from unquoted spaces in the path being split into separate args — fixed in **3.0.0** (argv array, no shell). Closing 🙏.
