### ISSUE TITLE
node_modules/webp-converter/temp not created at npm install

### ISSUE THREAD

**Issue by aFagot64** [scionoftech/webp-converter#41]
The directory node_modules/webp-converter/**temp** is requested for performing the conversion, but is not created at npm install.

Complexify installation as the directory temp needs to be created 'by hand' after fresh install.

{ Error: ENOENT: no such file or directory, open '/myProject/node_modules/webp-converter/temp/3d51e039-d615-4569-84b8-ee5f8d73d459.jpg'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at base64_to_image (/myProject/node_modules/webp-converter/src/buffer_utils.js:30:8)
    
   ....

**Comment by Givemeurcookies** [comment]
The project has been deprecated by it's author. I intend to maintain the project in my fork https://github.com/Givemeurcookies/promised-webp-converter
Please re-open the issue there and I'll address it when I have time.

**Comment by ads05henet** [comment]
in creating my project I created the following lines.

```
     new Promise((resolve, reject) => {
        fs.access('./node_modules/webp-converter/temp', (errer) => {
          if (errer) {
            fs.mkdirSync('./node_modules/webp-converter/temp')
            resolve()
          }
        })
      })
```

So I used the image for the container
version **node:14-buster-slim**

**Comment by scionoftech** [comment]
Fixed 🙏 — intermediate files now default to `os.tmpdir()` and are created on demand (and cleaned up afterwards), so there's no missing `temp/` on a fresh install. Closing.
