### ISSUE TITLE
Error in uploading image Error: ENOENT: no such file or directory, open '/home/lenovo/.webpack/temp/eb205475-2de3-41fd-a4ed-b3ab71906501.undefined'Error in uploading image Error: ENOENT: no such file or directory, open '/home/lenovo/.webpack/temp/eb205475-2de3-41fd-a4ed-b3ab71906501.undefined'

### ISSUE THREAD

**Issue by Jitenda-singh** [scionoftech/webp-converter#51]

**Comment by bramtechs** [comment]
Similar error here.

```
Error: ENOENT: no such file or directory, open '/home/bram/dev/basileusart.online/node_modules/webp-converter/temp/69fa2c6f-555d-4772-88dc-19ea8bcfd296.jpg'
    at Object.openSync (/home/bram/dev/basileusart.online/lib/fs.js:600:3)
    at Object.writeFileSync (/home/bram/dev/basileusart.online/lib/fs.js:2221:35)
    at base64_to_image (/home/bram/dev/basileusart.online/node_modules/webp-converter/src/buffer_utils.js:30:8)
    at Object.base64str2webp (/home/bram/dev/basileusart.online/node_modules/webp-converter/src/buffer_utils.js:55:18)
    at Object.str2webpstr (/home/bram/dev/basileusart.online/node_modules/webp-converter/src/webpconverter.js:25:23)
    at _callee2$ (/home/bram/dev/basileusart.online/src/thumbs.js:62:39)
    at tryCatch (/home/bram/dev/basileusart.online/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/bram/dev/basileusart.online/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.next (/home/bram/dev/basileusart.online/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/bram/dev/basileusart.online/src/thumbs.js:110:234) {errno: -2, syscall: 'open', code: 'ENOENT', path: '/home/bram/dev/basileusart.online/node_modules…temp/69fa2c6f-555d-4772-88dc-19ea8bcfd296.jpg', stack: 'Error: ENOENT: no such file or directory, ope…dev/basileusart.online/src/thumbs.js:110:234)', …}
```

**Comment by Takiyo0** [comment]
hey, i found the solution by simply create a `temp` folder inside the webp-converter's node_modules
<img width="275" alt="image" src="https://github.com/scionoftech/webp-converter/assets/60313514/37a23a41-4fb1-4072-a134-c6db8dfe6e8d">

**Comment by scionoftech** [comment]
Two parts here: the temp directory is now created on demand under `os.tmpdir()` (fixes the ENOENT), and the `.undefined` extension means `image_type` was `undefined` — pass a valid type such as `'jpg'`. Closing — please reopen if it persists on the latest release. 🙏
